# -*- coding: utf-8 -*-
"""Python_Class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18s9AayFB6Ol_5kg4bA-2G1p2_D1IH4z3

# Python code
"""

print('This is my first python ')

# this is  a comment

#Declaring data type in variable

# A variable name must start with a letter or the underscore character
# A variable name cannot start with a number
# A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
# Variable names are case-sensitive (age, Age and AGE are three different variables)
# A variable name cannot be any of the Python keywords.

a = 10

print(a)

type(a)

b = 10.10

b

type(b)

c = 'This is a string '

type(c)

d = True

type(d)

x, y, z = 'Reddy', 6, 8

x, y, z

# names cannot start with a? number
# names cannot use spaces
# no special char's
# PEP python enhancement praposal
# camelCase

# List is ordered sequence of Objects

lt = [23, 41, 66, 78, 100]

lt

lt2 = [23.5, 12.2, 25.9, 6.6, True, 'Reddy']

lt2

lt3 = [1, 2.5, "Raj", lt, lt2]

lt3

lt3[2]

lt3[3][2]

# Dict
# unordered collection of key value pairs

dt = {"name":'Reddy',
      "age":24,
      "email": 'reddy@gmail.com',
      "location" : 'Sklm'}

dt["name"]

# set
# ordered collection of unique data

st = {'reddy@gmail.com', 'reddy@gmail.com', 'reddy@yahoo.com', 'reddy@yahoo.com'}

st

#Tuple

tp = ('some important things that does not change', 'AI', 'VR', 'ML')

tp.index('AI')

multilineString = """ This is a
multiline
string
written in 4 lines"""

print(multilineString)

# Builtin methods of list

lst = ['Reddy', 24, 'Windows', 'Web dev']

lst

lst.append("Raju")

lst

lst.index("Raju")

lst.pop() # removes last one in the list

lst

lst.remove(24) # removes any data from the list

lst

lst.insert(2, 'manoj')

lst

dit = {"name":"Reddy", "age":24, "email": "reddy@gmail.com"}

dit.keys()

dit.values()

dit.get("email")

dit["email"]

dit["loc"] # gives error if undefined key is given

dit.get("loc") # get does not gives error if undefuned key is given

dit.clear()

dit

dit

dit.update({"name" : "Rajasekhara Reddy"})

dit

"""# Control Flow

## Comparision Operatior
"""

# Comparision operatior

a = 10;
b = 20;
c = 10;

(a == c)

(a != b)

(a > b)

(a < b)

(a <= b)

(a>= c)

# Logical operatiors
# AND
# OR
# NOT

tf_light = 'green'
tf = 'empty'

tf_light == 'green' and tf == 'empty'

tf_light == 'red' and tf == 'empty'

tf_light == 'green' or tf == 'empty'

"""# If Else"""

is_hungry = "Yes"

if (is_hungry == "Yes"):
  print("Order food from Zomatio")
  print("may be order chicken")
  print("Pay using Card")
else:
  print("Ignore orders")

# if elif else

marks = 81

if(marks > 90):
  print("A+++")
elif marks > 80:
  print("A++")
elif marks > 70:
  print('A+')
elif marks > 60:
  print('A')
else:
  print('Ok good')

"""# If else Calculator"""

# lets build a calculator

num1 = int(input("Enter num 1 : "))
num1

num2 = int(input("Enter num 2 : "))
num2

operation = input("enter operation (+,-,/,*) : " )
operation

if operation == "-":
  print(num1 - num2)
elif operation == "+":
  print(num1 + num2)
elif operation == "*":
  print(num1 * num2)
elif operation == "/":
  print(num1 / num2)
else:
  print("Invalid input")

"""# For Loop"""

lt = ['Reddy', 'Sai', 'Ravi', 'Yadav', 'Suresh']

lt

for temp in lt:
  print(temp)

